### ISSUE TITLE
AttributeError when calling stripe.Invoice.retrieve: module 'stripe.api_resources' has no attribute 'LineItem'

### ISSUE THREAD

**Issue by alanhamlett** [stripe/stripe-python#667]
Might be related to #655, after upgrading to 2.49.0 I'm getting exceptions when calling `stripe.Invoice.retrieve` that's definitely a stripe-python bug:

```
File "/opt/wakatime/current/wakatime/models/billing.py", line 1888, in create_stripe_receipt
    invoice = stripe.Invoice.retrieve(invoice_id)
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/api_resources/abstract/api_resource.py", line 12, in retrieve
    instance.refresh()
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/api_resources/abstract/api_resource.py", line 16, in refresh
    self.refresh_from(self.request("get", self.instance_url()))
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/stripe_object.py", line 246, in request
    response, api_key, self.stripe_version, self.stripe_account
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/util.py", line 165, in convert_to_stripe_object
    klass = get_object_classes().get(
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/util.py", line 135, in get_object_classes
    from stripe.object_classes import OBJECT_CLASSES
  File "/opt/wakatime/current/venv/lib/python3.6/site-packages/stripe/object_classes.py", line 49, in <module>
    api_resources.LineItem.OBJECT_NAME: api_resources.LineItem,
AttributeError: module 'stripe.api_resources' has no attribute 'LineItem'
```

**Comment by alanhamlett** [comment]
Are these object classes loaded at runtime? Maybe this isn't a bug and related to the file containing `LineItem` being removed during a partial release where the code running on the server was an older version of stripe-python but the code on filesystem was the new version.
